Removed "stig-build-windows-medium" because current version 1.5.1 does not support the Parent Image OS Version of Microsoft Windows Server 2022. For more info refer to https://docs.aws.amazon.com/imagebuilder/latest/userguide/toe-stig.html
Error: error creating Image Builder Image Recipe: InvalidParameterValueException: The value supplied for parameter 'components' is not valid. Component ARN 'arn:aws:imagebuilder:eu-west-2:593778046527:component/stig-build-windows-medium/1.5.1/1' does not support the Parent Image OS Version of Microsoft Windows Server 2022.